#!/bin/bash
# Append QEMU -cpu kvm-poll-control=on,kvm-hint-dedicated=on options for cpuidle-haltpoll

declare -a opts

i=0
is_cpu=0
for opt in "$@"; do
  if [ "$is_cpu" -eq 1 ]; then
    opts[i]="$opt,kvm-poll-control=on,kvm-hint-dedicated=on"
  else
    opts[i]="$opt"
  fi
  if [ "$opt" = "-cpu" ]; then
    is_cpu=1
  else
    is_cpu=0
  fi
  i=$((i + 1))
done

exec /root/qemu/x86_64-softmmu/qemu-system-x86_64 "${opts[@]}"
